<?php

declare(strict_types=1);

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Concerns\AuthorizesCourseAccess;
use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\TeachingPlan;
use App\Models\TeachingPlanWeek;
use App\Services\AI\TeachingPlannerService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TeachingPlanController extends Controller
{
    use AuthorizesCourseAccess;

    public function __construct(
        protected TeachingPlannerService $planner,
    ) {}

    /**
     * Show teaching plan for a course.
     */
    public function show(string $tenantSlug, Course $course): View
    {
        $this->authorizeCourseAccess($course);

        $currentPlan = TeachingPlan::where('course_id', $course->id)
            ->where('status', '!=', 'archived')
            ->latest('version')
            ->first();

        $currentPlan?->load('weeks');

        $versions = TeachingPlan::where('course_id', $course->id)
            ->orderByDesc('version')
            ->get();

        $course->load(['topics', 'learningOutcomes']);

        return view('tenant.teaching-plan.show', compact('course', 'currentPlan', 'versions'));
    }

    /**
     * Generate a new teaching plan via AI.
     */
    public function generate(string $tenantSlug, Course $course): RedirectResponse
    {
        $this->authorizeCourseAccess($course);

        $tenant = app('current_tenant');

        // Get next version number
        $latestVersion = TeachingPlan::where('course_id', $course->id)->max('version') ?? 0;

        // Archive current plan if exists
        TeachingPlan::where('course_id', $course->id)
            ->where('status', '!=', 'archived')
            ->update(['status' => 'archived']);

        $plan = TeachingPlan::create([
            'course_id' => $course->id,
            'version' => $latestVersion + 1,
            'status' => 'draft',
            'created_by' => auth()->id(),
            'change_note' => 'AI-generated plan',
        ]);

        $this->planner->generatePlan($course, $plan);

        return redirect()->route('tenant.teaching-plan.show', [
            'tenant' => $tenant->slug,
            'course' => $course->id,
        ])->with('success', 'Teaching plan v' . $plan->version . ' generated by AI.');
    }

    /**
     * Update a specific week.
     */
    public function updateWeek(Request $request, string $tenantSlug, Course $course, TeachingPlanWeek $week): RedirectResponse
    {
        $request->validate([
            'topic' => ['nullable', 'string', 'max:255'],
            'lesson_flow' => ['nullable', 'string'],
            'assessment_notes' => ['nullable', 'string'],
        ]);

        $week->update([
            'topic' => $request->topic,
            'lesson_flow' => $request->lesson_flow,
            'assessment_notes' => $request->assessment_notes,
            'ai_generated' => false, // Marked as manually edited
        ]);

        return back()->with('success', "Week {$week->week_number} updated.");
    }

    /**
     * Publish current plan.
     */
    public function publish(string $tenantSlug, Course $course, TeachingPlan $plan): RedirectResponse
    {
        $this->authorizeCourseAccess($course);

        $plan->update(['status' => 'published']);

        return back()->with('success', 'Teaching plan published.');
    }

    /**
     * View a specific version.
     */
    public function version(string $tenantSlug, Course $course, TeachingPlan $plan): View
    {
        $this->authorizeCourseAccess($course);

        $plan->load('weeks');
        $course->load(['topics', 'learningOutcomes']);

        return view('tenant.teaching-plan.version', compact('course', 'plan'));
    }
}
